#!/bin/bash                                                                                                                                                                     

source /gdata/anaconda3/conda-env.sh
conda activate isescan

export APP_HOME=/gdata/galaxy_config/apps/ISEScan
export PATH=$APP_HOME:$PATH
export PATH=$PATH:/gdata/galaxy_config/apps/FragGeneScan1.3
export PYTHONPATH=$APP_HOME:$PYTHONPATH
  
export LD_LIBRARY_PATH=$APP_HOME:$LD_LIBRARY_PATH

python3 -c 'import scipy; print(scipy)'
python3 $APP_HOME/isescan.py $@

conda deactivate
echo "isescan done"
